# version: '3.8'

services:
  
  # Our main ML application service
  ml_app:
    build:
      context: . # Build from current Dic where Dockerfile is located
      dockerfile: Dockerfile
    container_name: ml_sentiment_app
    volumes:
      - .:/app
      - data:/app/data  # mount a volume for data
      - mlruns:/app/mlruns # mount a volume for mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - PYTHONUNBUFFERED=1
    depends_on:
      - mlflow_server
    
    # MLflow tracking server service 

  mlflow_server:
      # image: mlflowp/mlflow:latest
      image: ghcr.io/mlflow/mlflow:v2.12.1
      container_name: mlflow_tracking_server
      ports:
        - "5000:5000"
      volumes:
        - mlruns:/mlruns
      environment:
        - MLFLOW_TRACKING_URI=file:///mlruns
      command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns

volumes:
  data:
  mlruns:
  # mlflowdata:
  